version: '2'
services:
  headless-client:
    build: dependencies/headless-client
    links:
      - redis
      - postgres
    environment: &environment
      - TOKEN_APP_ID=0x534c3a4f2a9bb0a2d042bada822a81313b249442
      - TOKEN_APP_PAYMENT_ADDRESS=0xeb42c517314cf1694db08e648ecd2ff8246ff99d
      - TOKEN_APP_USERNAME=ParkingBot
      - TOKEN_APP_NAME=ParkingBot
      - TOKEN_APP_AVATAR=ParkingBot
      - TOKEN_APP_SEED=napkin tuition upper afford lazy drift travel blush excite hope unaware cereal
      - REDIS_URL=redis://h:rlcMWNrxXgqS0xM8aWCYuE0R@redis:6379
      - DATABASE_URL=postgres://token:va5uOdJBqu2dZ1@postgres:5432/token
    volumes:
      - ./config/docker.yml:/usr/src/headless-client/config.yml
      - ./attachments:/usr/src/headless-client/attachments
  bot:
    build: .
    links:
      - redis
      - postgres
    environment: *environment
    volumes:
      - ./config/docker.yml:/usr/src/bot/config.yml
      - ./src:/usr/src/bot/src
  redis:
    build: dependencies/redis
    ports:
      - 6379
  postgres:
    image: postgres:9.6
    ports:
      - 15432
    environment:
      - POSTGRES_PASSWORD=va5uOdJBqu2dZ1
      - POSTGRES_USER=token
      - POSTGRES_DB=token
